#!/bin/bash

# bail on errors
set -eu

function banner() {
  printf '\e[1;37;43m[%s] %-72s\e[0m\n' `date '+%H:%M:%S'` "vagrant_provision: $1"
}

# packages needed for building ruby
banner "Packages..."
sudo apt-get -y install git-core
sudo apt-get -y install build-essential checkinstall libffi-dev libreadline-gplv2-dev libncurses5-dev libssl-dev libyaml-dev zlib1g-dev

# rbenv
banner "Rbenv..."
if [ ! -d ~/.rbenv ] ; then
  git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
fi
if [ ! -d ~/.rbenv/plugins/ruby-build ] ; then
  git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

# add rbenv to .bashrc
if ! grep -q 'vagrant provisioning' ~/.bashrc ; then
  cat >> ~/.bashrc <<"EOF"
# added by vagrant provisioning
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
EOF

  # make sure we pickup rbenv too!
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# no rdoc, please
echo 'gem: --no-ri --no-rdoc' > ~/.gemrc

# now install ruby
banner "Ruby..."
rbenv install 2.0.0-p353
rbenv global 2.0.0-p353
ruby -v

# and gems
banner "Gems..."
gem update --system
gem install bundler
rbenv rehash